name: Deploy to Azure App Service

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: コードをチェックアウト
        uses: actions/checkout@v4

      - name: Azureにデプロイ
        uses: azure/webapps-deploy@v2
        with:
          app-name: codebridge-t-k-haru
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
          package: .
